/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SMART_PKG_DELIVERY_SMART_PKG_DELIVERY_PB_H_INCLUDED
#define PB_SMART_PKG_DELIVERY_SMART_PKG_DELIVERY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* ❔ Sockets for Communication
    - Server (c++)
    - Address Recognizer (c or python)
    - User (c++)
    - Delivery Robot (c++)
    - Elevator (c) */
typedef enum _smart_pkg_delivery_NodeType {
    smart_pkg_delivery_NodeType_UNSPECIFIED = 0,
    smart_pkg_delivery_NodeType_SERVER = 1,
    smart_pkg_delivery_NodeType_CLIENT_ADDRESS_RECOGNIZER = 2,
    smart_pkg_delivery_NodeType_CLIENT_USER = 3,
    smart_pkg_delivery_NodeType_CLIENT_DELIVERY_ROBOT = 4,
    smart_pkg_delivery_NodeType_CLIENT_ELEVATOR = 5
} smart_pkg_delivery_NodeType;

typedef enum _smart_pkg_delivery_AckStatus_StatusCode {
    smart_pkg_delivery_AckStatus_StatusCode_UNSPECIFIED = 0,
    smart_pkg_delivery_AckStatus_StatusCode_ACK_RECEIVED = 1,
    smart_pkg_delivery_AckStatus_StatusCode_ACK_INVALID = 2
} smart_pkg_delivery_AckStatus_StatusCode;

typedef enum _smart_pkg_delivery_ExecutionStatus_StatusCode {
    smart_pkg_delivery_ExecutionStatus_StatusCode_UNSPECIFIED = 0,
    smart_pkg_delivery_ExecutionStatus_StatusCode_SUCCESS = 1,
    smart_pkg_delivery_ExecutionStatus_StatusCode_FAILED = 2
} smart_pkg_delivery_ExecutionStatus_StatusCode;

typedef enum _smart_pkg_delivery_Elevator_DoorOpenStatus {
    smart_pkg_delivery_Elevator_DoorOpenStatus_UNSPECIFIED = 0,
    smart_pkg_delivery_Elevator_DoorOpenStatus_CLOSED = 1,
    smart_pkg_delivery_Elevator_DoorOpenStatus_OPEN = 2
} smart_pkg_delivery_Elevator_DoorOpenStatus;

typedef enum _smart_pkg_delivery_DeliveryRobot_DeliveryStatus {
    smart_pkg_delivery_DeliveryRobot_DeliveryStatus_UNSPECIFIED = 0,
    smart_pkg_delivery_DeliveryRobot_DeliveryStatus_PENDING = 1,
    smart_pkg_delivery_DeliveryRobot_DeliveryStatus_IN_TRANSIT = 2,
    smart_pkg_delivery_DeliveryRobot_DeliveryStatus_DELIVERED = 3
} smart_pkg_delivery_DeliveryRobot_DeliveryStatus;

/* Struct definitions */
/* -------------------------
 -------------------------
 Indicates whether a Request has been successfully received by the Destination from the Source. */
typedef struct _smart_pkg_delivery_AckStatus {
    bool has_status_code;
    smart_pkg_delivery_AckStatus_StatusCode status_code;
    bool has_message;
    char message[256];
} smart_pkg_delivery_AckStatus;

/* Indicates the execution result of the received Request. */
typedef struct _smart_pkg_delivery_ExecutionStatus {
    bool has_status_code;
    smart_pkg_delivery_ExecutionStatus_StatusCode status_code;
    bool has_message;
    char message[256];
} smart_pkg_delivery_ExecutionStatus;

/* -------------------------
 🌀 Request, Response, Event 🔪 Details
 -------------------------
 🔰 Sent by the client to identify itself during the initial registration. */
typedef struct _smart_pkg_delivery_ClientRegisterRequest {
    bool has_identity_type;
    smart_pkg_delivery_NodeType identity_type;
    bool has_identity_id;
    uint32_t identity_id;
    pb_callback_t identity_name;
} smart_pkg_delivery_ClientRegisterRequest;

typedef struct _smart_pkg_delivery_ClientRegisterResponse {
    char dummy_field;
} smart_pkg_delivery_ClientRegisterResponse;

typedef struct _smart_pkg_delivery_GetPkgInfosRequest {
    bool has_user_id;
    uint32_t user_id;
} smart_pkg_delivery_GetPkgInfosRequest;

typedef struct _smart_pkg_delivery_MoveDeliveryRobotResponse {
    char dummy_field;
} smart_pkg_delivery_MoveDeliveryRobotResponse;

typedef struct _smart_pkg_delivery_SetElevatorStatusResponse {
    char dummy_field;
} smart_pkg_delivery_SetElevatorStatusResponse;

typedef struct _smart_pkg_delivery_DeliveryStatusEvent {
    bool has_delivery_robot_id;
    uint32_t delivery_robot_id;
    bool has_delivery_status;
    smart_pkg_delivery_DeliveryRobot_DeliveryStatus delivery_status;
} smart_pkg_delivery_DeliveryStatusEvent;

typedef struct _smart_pkg_delivery_Elevator_Status {
    bool has_current_floor;
    uint32_t current_floor;
    bool has_door_open_status;
    smart_pkg_delivery_Elevator_DoorOpenStatus door_open_status;
} smart_pkg_delivery_Elevator_Status;

/* ------------------------- */
typedef struct _smart_pkg_delivery_SetElevatorStatusRequest {
    bool has_elevator_id;
    uint32_t elevator_id;
    bool has_elevator_status;
    smart_pkg_delivery_Elevator_Status elevator_status;
} smart_pkg_delivery_SetElevatorStatusRequest;

typedef struct _smart_pkg_delivery_ElevatorStatusEvent {
    bool has_elevator_id;
    uint32_t elevator_id;
    bool has_elevator_status;
    smart_pkg_delivery_Elevator_Status elevator_status;
} smart_pkg_delivery_ElevatorStatusEvent;

/* -------------------------
 🌀 Nodes
 -------------------------
 🛗 */
typedef struct _smart_pkg_delivery_Elevator {
    bool has_id;
    uint32_t id;
    bool has_status;
    smart_pkg_delivery_Elevator_Status status;
} smart_pkg_delivery_Elevator;

/* 🚛 */
typedef struct _smart_pkg_delivery_DeliveryRobot {
    bool has_id;
    uint32_t id;
    /* Status status = 2; */
    bool has_delivery_status;
    smart_pkg_delivery_DeliveryRobot_DeliveryStatus delivery_status;
} smart_pkg_delivery_DeliveryRobot;

/* 🔒 */
typedef struct _smart_pkg_delivery_PkgRoom_Locker {
    bool has_locker_id;
    uint32_t locker_id;
    bool has_access_code;
    char access_code[32];
    bool has_pkg_id;
    uint32_t pkg_id;
} smart_pkg_delivery_PkgRoom_Locker;

/* 🏬 Package Room */
typedef struct _smart_pkg_delivery_PkgRoom {
    bool has_id;
    uint32_t id;
    pb_size_t lockers_count;
    smart_pkg_delivery_PkgRoom_Locker lockers[10];
} smart_pkg_delivery_PkgRoom;

typedef struct _smart_pkg_delivery_AptAddress {
    bool has_apt_complex;
    char apt_complex[128];
    bool has_building_num;
    uint32_t building_num;
    bool has_unit_num;
    uint32_t unit_num;
} smart_pkg_delivery_AptAddress;

typedef struct _smart_pkg_delivery_MoveDeliveryRobotRequest {
    bool has_delivery_robot_id;
    uint32_t delivery_robot_id;
    bool has_destination_address;
    smart_pkg_delivery_AptAddress destination_address;
} smart_pkg_delivery_MoveDeliveryRobotRequest;

/* 📨 A request message that expects a response from the destination. */
typedef struct _smart_pkg_delivery_Request {
    pb_size_t which_request_type;
    union {
        smart_pkg_delivery_ClientRegisterRequest client_register_request;
        /* user (c++) ---> server */
        smart_pkg_delivery_GetPkgInfosRequest get_pkg_infos_request;
        /* client-delivery_robot (c++) ---> server ---> client-elevator (c) */
        smart_pkg_delivery_SetElevatorStatusRequest set_elevator_status_request;
        /* client-user (c++) ---> server ---> client-delivery_robot (c++) */
        smart_pkg_delivery_MoveDeliveryRobotRequest move_delivery_robot_request;
    } request_type;
} smart_pkg_delivery_Request;

/* -------------------------
 ------------------------- */
typedef struct _smart_pkg_delivery_PkgArrivalEvent {
    bool has_address;
    smart_pkg_delivery_AptAddress address; /* Pkg.Status pkg_status = 2; */
} smart_pkg_delivery_PkgArrivalEvent;

/* ⏬ Events; A one-way message that notifies the system about status updates without expecting any response. */
typedef struct _smart_pkg_delivery_NodeEvent {
    pb_size_t which_event_type;
    union {
        /* client-pkg_room (python) ---> server */
        smart_pkg_delivery_PkgArrivalEvent pkg_arrival_event;
        /* client-elevator (c++) ---> server ---> client-delivery_robot (c++) */
        smart_pkg_delivery_ElevatorStatusEvent elevator_status_event;
        /* client-delivery_robot (c++) ---> server */
        smart_pkg_delivery_DeliveryStatusEvent delivery_status_event;
    } event_type;
} smart_pkg_delivery_NodeEvent;

/* 👤 User (Wall Pad) */
typedef struct _smart_pkg_delivery_User {
    bool has_id;
    uint32_t id;
    bool has_address;
    smart_pkg_delivery_AptAddress address;
} smart_pkg_delivery_User;

/* 📦 */
typedef struct _smart_pkg_delivery_Pkg {
    bool has_id;
    uint32_t id;
    bool has_address;
    smart_pkg_delivery_AptAddress address;
    bool has_sender_id;
    uint32_t sender_id;
    bool has_receiver_id;
    uint32_t receiver_id;
} smart_pkg_delivery_Pkg;

typedef struct _smart_pkg_delivery_GetPkgInfoResponse {
    pb_size_t pkgs_count;
    smart_pkg_delivery_Pkg pkgs[10];
} smart_pkg_delivery_GetPkgInfoResponse;

/* 📩 A response message to a request that does not expect further replies, including ✅ ACK. */
typedef struct _smart_pkg_delivery_Response {
    bool has_ack_status;
    smart_pkg_delivery_AckStatus ack_status;
    bool has_execution_status;
    smart_pkg_delivery_ExecutionStatus execution_status;
    pb_size_t which_response_type;
    union {
        smart_pkg_delivery_ClientRegisterResponse client_register_response;
        /* server ---> user (c++) */
        smart_pkg_delivery_GetPkgInfoResponse get_pkg_info_response;
        /* client-elevator (c) ---> server ---> client-delivery_robot (c++) */
        smart_pkg_delivery_SetElevatorStatusResponse set_elevator_status_response;
        /* client-delivery_robot (c++) ---> server ---> client-user (c++) */
        smart_pkg_delivery_MoveDeliveryRobotResponse move_delivery_robot_response;
    } response_type;
} smart_pkg_delivery_Response;

/* -------------------------
 🌀 Request, Response, Event (like Notification)
 -------------------------
 Wrapper to distinguish between Request, Response, and Event messages.
    ❔ Name `ExchangeMessage` is inspired by the message exchange process after HTTPS Handshake. */
typedef struct _smart_pkg_delivery_InteractionMsg {
    /* 📝 Note that src_* are set in Server. Never set manually in Client. */
    bool has_src_type;
    smart_pkg_delivery_NodeType src_type;
    bool has_src_id;
    uint32_t src_id;
    pb_callback_t src_name;
    /*  */
    bool has_dest_type;
    smart_pkg_delivery_NodeType dest_type;
    bool has_dest_id;
    uint32_t dest_id;
    pb_callback_t dest_name;
    pb_size_t which_msg_type;
    union {
        smart_pkg_delivery_Request request;
        smart_pkg_delivery_Response response;
        smart_pkg_delivery_NodeEvent node_event;
    } msg_type;
} smart_pkg_delivery_InteractionMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _smart_pkg_delivery_NodeType_MIN smart_pkg_delivery_NodeType_UNSPECIFIED
#define _smart_pkg_delivery_NodeType_MAX smart_pkg_delivery_NodeType_CLIENT_ELEVATOR
#define _smart_pkg_delivery_NodeType_ARRAYSIZE ((smart_pkg_delivery_NodeType)(smart_pkg_delivery_NodeType_CLIENT_ELEVATOR+1))

#define _smart_pkg_delivery_AckStatus_StatusCode_MIN smart_pkg_delivery_AckStatus_StatusCode_UNSPECIFIED
#define _smart_pkg_delivery_AckStatus_StatusCode_MAX smart_pkg_delivery_AckStatus_StatusCode_ACK_INVALID
#define _smart_pkg_delivery_AckStatus_StatusCode_ARRAYSIZE ((smart_pkg_delivery_AckStatus_StatusCode)(smart_pkg_delivery_AckStatus_StatusCode_ACK_INVALID+1))

#define _smart_pkg_delivery_ExecutionStatus_StatusCode_MIN smart_pkg_delivery_ExecutionStatus_StatusCode_UNSPECIFIED
#define _smart_pkg_delivery_ExecutionStatus_StatusCode_MAX smart_pkg_delivery_ExecutionStatus_StatusCode_FAILED
#define _smart_pkg_delivery_ExecutionStatus_StatusCode_ARRAYSIZE ((smart_pkg_delivery_ExecutionStatus_StatusCode)(smart_pkg_delivery_ExecutionStatus_StatusCode_FAILED+1))

#define _smart_pkg_delivery_Elevator_DoorOpenStatus_MIN smart_pkg_delivery_Elevator_DoorOpenStatus_UNSPECIFIED
#define _smart_pkg_delivery_Elevator_DoorOpenStatus_MAX smart_pkg_delivery_Elevator_DoorOpenStatus_OPEN
#define _smart_pkg_delivery_Elevator_DoorOpenStatus_ARRAYSIZE ((smart_pkg_delivery_Elevator_DoorOpenStatus)(smart_pkg_delivery_Elevator_DoorOpenStatus_OPEN+1))

#define _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_MIN smart_pkg_delivery_DeliveryRobot_DeliveryStatus_UNSPECIFIED
#define _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_MAX smart_pkg_delivery_DeliveryRobot_DeliveryStatus_DELIVERED
#define _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_ARRAYSIZE ((smart_pkg_delivery_DeliveryRobot_DeliveryStatus)(smart_pkg_delivery_DeliveryRobot_DeliveryStatus_DELIVERED+1))

#define smart_pkg_delivery_InteractionMsg_src_type_ENUMTYPE smart_pkg_delivery_NodeType
#define smart_pkg_delivery_InteractionMsg_dest_type_ENUMTYPE smart_pkg_delivery_NodeType




#define smart_pkg_delivery_AckStatus_status_code_ENUMTYPE smart_pkg_delivery_AckStatus_StatusCode

#define smart_pkg_delivery_ExecutionStatus_status_code_ENUMTYPE smart_pkg_delivery_ExecutionStatus_StatusCode

#define smart_pkg_delivery_ClientRegisterRequest_identity_type_ENUMTYPE smart_pkg_delivery_NodeType










#define smart_pkg_delivery_DeliveryStatusEvent_delivery_status_ENUMTYPE smart_pkg_delivery_DeliveryRobot_DeliveryStatus


#define smart_pkg_delivery_Elevator_Status_door_open_status_ENUMTYPE smart_pkg_delivery_Elevator_DoorOpenStatus

#define smart_pkg_delivery_DeliveryRobot_delivery_status_ENUMTYPE smart_pkg_delivery_DeliveryRobot_DeliveryStatus







/* Initializer values for message structs */
#define smart_pkg_delivery_InteractionMsg_init_default {false, _smart_pkg_delivery_NodeType_MIN, false, 0, {{NULL}, NULL}, false, _smart_pkg_delivery_NodeType_MIN, false, 0, {{NULL}, NULL}, 0, {smart_pkg_delivery_Request_init_default}}
#define smart_pkg_delivery_Request_init_default  {0, {smart_pkg_delivery_ClientRegisterRequest_init_default}}
#define smart_pkg_delivery_Response_init_default {false, smart_pkg_delivery_AckStatus_init_default, false, smart_pkg_delivery_ExecutionStatus_init_default, 0, {smart_pkg_delivery_ClientRegisterResponse_init_default}}
#define smart_pkg_delivery_NodeEvent_init_default {0, {smart_pkg_delivery_PkgArrivalEvent_init_default}}
#define smart_pkg_delivery_AckStatus_init_default {false, _smart_pkg_delivery_AckStatus_StatusCode_MIN, false, ""}
#define smart_pkg_delivery_ExecutionStatus_init_default {false, _smart_pkg_delivery_ExecutionStatus_StatusCode_MIN, false, ""}
#define smart_pkg_delivery_ClientRegisterRequest_init_default {false, _smart_pkg_delivery_NodeType_MIN, false, 0, {{NULL}, NULL}}
#define smart_pkg_delivery_ClientRegisterResponse_init_default {0}
#define smart_pkg_delivery_GetPkgInfosRequest_init_default {false, 0}
#define smart_pkg_delivery_GetPkgInfoResponse_init_default {0, {smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default, smart_pkg_delivery_Pkg_init_default}}
#define smart_pkg_delivery_MoveDeliveryRobotRequest_init_default {false, 0, false, smart_pkg_delivery_AptAddress_init_default}
#define smart_pkg_delivery_MoveDeliveryRobotResponse_init_default {0}
#define smart_pkg_delivery_SetElevatorStatusRequest_init_default {false, 0, false, smart_pkg_delivery_Elevator_Status_init_default}
#define smart_pkg_delivery_SetElevatorStatusResponse_init_default {0}
#define smart_pkg_delivery_PkgArrivalEvent_init_default {false, smart_pkg_delivery_AptAddress_init_default}
#define smart_pkg_delivery_ElevatorStatusEvent_init_default {false, 0, false, smart_pkg_delivery_Elevator_Status_init_default}
#define smart_pkg_delivery_DeliveryStatusEvent_init_default {false, 0, false, _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_MIN}
#define smart_pkg_delivery_Elevator_init_default {false, 0, false, smart_pkg_delivery_Elevator_Status_init_default}
#define smart_pkg_delivery_Elevator_Status_init_default {false, 0, false, _smart_pkg_delivery_Elevator_DoorOpenStatus_MIN}
#define smart_pkg_delivery_DeliveryRobot_init_default {false, 0, false, _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_MIN}
#define smart_pkg_delivery_PkgRoom_init_default  {false, 0, 0, {smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default, smart_pkg_delivery_PkgRoom_Locker_init_default}}
#define smart_pkg_delivery_PkgRoom_Locker_init_default {false, 0, false, "", false, 0}
#define smart_pkg_delivery_User_init_default     {false, 0, false, smart_pkg_delivery_AptAddress_init_default}
#define smart_pkg_delivery_Pkg_init_default      {false, 0, false, smart_pkg_delivery_AptAddress_init_default, false, 0, false, 0}
#define smart_pkg_delivery_AptAddress_init_default {false, "", false, 0, false, 0}
#define smart_pkg_delivery_InteractionMsg_init_zero {false, _smart_pkg_delivery_NodeType_MIN, false, 0, {{NULL}, NULL}, false, _smart_pkg_delivery_NodeType_MIN, false, 0, {{NULL}, NULL}, 0, {smart_pkg_delivery_Request_init_zero}}
#define smart_pkg_delivery_Request_init_zero     {0, {smart_pkg_delivery_ClientRegisterRequest_init_zero}}
#define smart_pkg_delivery_Response_init_zero    {false, smart_pkg_delivery_AckStatus_init_zero, false, smart_pkg_delivery_ExecutionStatus_init_zero, 0, {smart_pkg_delivery_ClientRegisterResponse_init_zero}}
#define smart_pkg_delivery_NodeEvent_init_zero   {0, {smart_pkg_delivery_PkgArrivalEvent_init_zero}}
#define smart_pkg_delivery_AckStatus_init_zero   {false, _smart_pkg_delivery_AckStatus_StatusCode_MIN, false, ""}
#define smart_pkg_delivery_ExecutionStatus_init_zero {false, _smart_pkg_delivery_ExecutionStatus_StatusCode_MIN, false, ""}
#define smart_pkg_delivery_ClientRegisterRequest_init_zero {false, _smart_pkg_delivery_NodeType_MIN, false, 0, {{NULL}, NULL}}
#define smart_pkg_delivery_ClientRegisterResponse_init_zero {0}
#define smart_pkg_delivery_GetPkgInfosRequest_init_zero {false, 0}
#define smart_pkg_delivery_GetPkgInfoResponse_init_zero {0, {smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero, smart_pkg_delivery_Pkg_init_zero}}
#define smart_pkg_delivery_MoveDeliveryRobotRequest_init_zero {false, 0, false, smart_pkg_delivery_AptAddress_init_zero}
#define smart_pkg_delivery_MoveDeliveryRobotResponse_init_zero {0}
#define smart_pkg_delivery_SetElevatorStatusRequest_init_zero {false, 0, false, smart_pkg_delivery_Elevator_Status_init_zero}
#define smart_pkg_delivery_SetElevatorStatusResponse_init_zero {0}
#define smart_pkg_delivery_PkgArrivalEvent_init_zero {false, smart_pkg_delivery_AptAddress_init_zero}
#define smart_pkg_delivery_ElevatorStatusEvent_init_zero {false, 0, false, smart_pkg_delivery_Elevator_Status_init_zero}
#define smart_pkg_delivery_DeliveryStatusEvent_init_zero {false, 0, false, _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_MIN}
#define smart_pkg_delivery_Elevator_init_zero    {false, 0, false, smart_pkg_delivery_Elevator_Status_init_zero}
#define smart_pkg_delivery_Elevator_Status_init_zero {false, 0, false, _smart_pkg_delivery_Elevator_DoorOpenStatus_MIN}
#define smart_pkg_delivery_DeliveryRobot_init_zero {false, 0, false, _smart_pkg_delivery_DeliveryRobot_DeliveryStatus_MIN}
#define smart_pkg_delivery_PkgRoom_init_zero     {false, 0, 0, {smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero, smart_pkg_delivery_PkgRoom_Locker_init_zero}}
#define smart_pkg_delivery_PkgRoom_Locker_init_zero {false, 0, false, "", false, 0}
#define smart_pkg_delivery_User_init_zero        {false, 0, false, smart_pkg_delivery_AptAddress_init_zero}
#define smart_pkg_delivery_Pkg_init_zero         {false, 0, false, smart_pkg_delivery_AptAddress_init_zero, false, 0, false, 0}
#define smart_pkg_delivery_AptAddress_init_zero  {false, "", false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define smart_pkg_delivery_AckStatus_status_code_tag 1
#define smart_pkg_delivery_AckStatus_message_tag 2
#define smart_pkg_delivery_ExecutionStatus_status_code_tag 1
#define smart_pkg_delivery_ExecutionStatus_message_tag 2
#define smart_pkg_delivery_ClientRegisterRequest_identity_type_tag 1
#define smart_pkg_delivery_ClientRegisterRequest_identity_id_tag 2
#define smart_pkg_delivery_ClientRegisterRequest_identity_name_tag 3
#define smart_pkg_delivery_GetPkgInfosRequest_user_id_tag 1
#define smart_pkg_delivery_DeliveryStatusEvent_delivery_robot_id_tag 1
#define smart_pkg_delivery_DeliveryStatusEvent_delivery_status_tag 2
#define smart_pkg_delivery_Elevator_Status_current_floor_tag 1
#define smart_pkg_delivery_Elevator_Status_door_open_status_tag 2
#define smart_pkg_delivery_SetElevatorStatusRequest_elevator_id_tag 1
#define smart_pkg_delivery_SetElevatorStatusRequest_elevator_status_tag 2
#define smart_pkg_delivery_ElevatorStatusEvent_elevator_id_tag 1
#define smart_pkg_delivery_ElevatorStatusEvent_elevator_status_tag 2
#define smart_pkg_delivery_Elevator_id_tag       1
#define smart_pkg_delivery_Elevator_status_tag   2
#define smart_pkg_delivery_DeliveryRobot_id_tag  1
#define smart_pkg_delivery_DeliveryRobot_delivery_status_tag 3
#define smart_pkg_delivery_PkgRoom_Locker_locker_id_tag 1
#define smart_pkg_delivery_PkgRoom_Locker_access_code_tag 2
#define smart_pkg_delivery_PkgRoom_Locker_pkg_id_tag 3
#define smart_pkg_delivery_PkgRoom_id_tag        1
#define smart_pkg_delivery_PkgRoom_lockers_tag   2
#define smart_pkg_delivery_AptAddress_apt_complex_tag 1
#define smart_pkg_delivery_AptAddress_building_num_tag 2
#define smart_pkg_delivery_AptAddress_unit_num_tag 3
#define smart_pkg_delivery_MoveDeliveryRobotRequest_delivery_robot_id_tag 1
#define smart_pkg_delivery_MoveDeliveryRobotRequest_destination_address_tag 2
#define smart_pkg_delivery_Request_client_register_request_tag 1
#define smart_pkg_delivery_Request_get_pkg_infos_request_tag 2
#define smart_pkg_delivery_Request_set_elevator_status_request_tag 3
#define smart_pkg_delivery_Request_move_delivery_robot_request_tag 4
#define smart_pkg_delivery_PkgArrivalEvent_address_tag 1
#define smart_pkg_delivery_NodeEvent_pkg_arrival_event_tag 1
#define smart_pkg_delivery_NodeEvent_elevator_status_event_tag 2
#define smart_pkg_delivery_NodeEvent_delivery_status_event_tag 3
#define smart_pkg_delivery_User_id_tag           1
#define smart_pkg_delivery_User_address_tag      2
#define smart_pkg_delivery_Pkg_id_tag            1
#define smart_pkg_delivery_Pkg_address_tag       2
#define smart_pkg_delivery_Pkg_sender_id_tag     3
#define smart_pkg_delivery_Pkg_receiver_id_tag   4
#define smart_pkg_delivery_GetPkgInfoResponse_pkgs_tag 1
#define smart_pkg_delivery_Response_ack_status_tag 1
#define smart_pkg_delivery_Response_execution_status_tag 2
#define smart_pkg_delivery_Response_client_register_response_tag 3
#define smart_pkg_delivery_Response_get_pkg_info_response_tag 4
#define smart_pkg_delivery_Response_set_elevator_status_response_tag 5
#define smart_pkg_delivery_Response_move_delivery_robot_response_tag 6
#define smart_pkg_delivery_InteractionMsg_src_type_tag 1
#define smart_pkg_delivery_InteractionMsg_src_id_tag 2
#define smart_pkg_delivery_InteractionMsg_src_name_tag 3
#define smart_pkg_delivery_InteractionMsg_dest_type_tag 4
#define smart_pkg_delivery_InteractionMsg_dest_id_tag 5
#define smart_pkg_delivery_InteractionMsg_dest_name_tag 6
#define smart_pkg_delivery_InteractionMsg_request_tag 7
#define smart_pkg_delivery_InteractionMsg_response_tag 8
#define smart_pkg_delivery_InteractionMsg_node_event_tag 9

/* Struct field encoding specification for nanopb */
#define smart_pkg_delivery_InteractionMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    src_type,          1) \
X(a, STATIC,   OPTIONAL, UINT32,   src_id,            2) \
X(a, CALLBACK, OPTIONAL, STRING,   src_name,          3) \
X(a, STATIC,   OPTIONAL, UENUM,    dest_type,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   dest_id,           5) \
X(a, CALLBACK, OPTIONAL, STRING,   dest_name,         6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg_type,request,msg_type.request),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg_type,response,msg_type.response),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg_type,node_event,msg_type.node_event),   9)
#define smart_pkg_delivery_InteractionMsg_CALLBACK pb_default_field_callback
#define smart_pkg_delivery_InteractionMsg_DEFAULT NULL
#define smart_pkg_delivery_InteractionMsg_msg_type_request_MSGTYPE smart_pkg_delivery_Request
#define smart_pkg_delivery_InteractionMsg_msg_type_response_MSGTYPE smart_pkg_delivery_Response
#define smart_pkg_delivery_InteractionMsg_msg_type_node_event_MSGTYPE smart_pkg_delivery_NodeEvent

#define smart_pkg_delivery_Request_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,client_register_request,request_type.client_register_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,get_pkg_infos_request,request_type.get_pkg_infos_request),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,set_elevator_status_request,request_type.set_elevator_status_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request_type,move_delivery_robot_request,request_type.move_delivery_robot_request),   4)
#define smart_pkg_delivery_Request_CALLBACK NULL
#define smart_pkg_delivery_Request_DEFAULT NULL
#define smart_pkg_delivery_Request_request_type_client_register_request_MSGTYPE smart_pkg_delivery_ClientRegisterRequest
#define smart_pkg_delivery_Request_request_type_get_pkg_infos_request_MSGTYPE smart_pkg_delivery_GetPkgInfosRequest
#define smart_pkg_delivery_Request_request_type_set_elevator_status_request_MSGTYPE smart_pkg_delivery_SetElevatorStatusRequest
#define smart_pkg_delivery_Request_request_type_move_delivery_robot_request_MSGTYPE smart_pkg_delivery_MoveDeliveryRobotRequest

#define smart_pkg_delivery_Response_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ack_status,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  execution_status,   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,client_register_response,response_type.client_register_response),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,get_pkg_info_response,response_type.get_pkg_info_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,set_elevator_status_response,response_type.set_elevator_status_response),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response_type,move_delivery_robot_response,response_type.move_delivery_robot_response),   6)
#define smart_pkg_delivery_Response_CALLBACK NULL
#define smart_pkg_delivery_Response_DEFAULT NULL
#define smart_pkg_delivery_Response_ack_status_MSGTYPE smart_pkg_delivery_AckStatus
#define smart_pkg_delivery_Response_execution_status_MSGTYPE smart_pkg_delivery_ExecutionStatus
#define smart_pkg_delivery_Response_response_type_client_register_response_MSGTYPE smart_pkg_delivery_ClientRegisterResponse
#define smart_pkg_delivery_Response_response_type_get_pkg_info_response_MSGTYPE smart_pkg_delivery_GetPkgInfoResponse
#define smart_pkg_delivery_Response_response_type_set_elevator_status_response_MSGTYPE smart_pkg_delivery_SetElevatorStatusResponse
#define smart_pkg_delivery_Response_response_type_move_delivery_robot_response_MSGTYPE smart_pkg_delivery_MoveDeliveryRobotResponse

#define smart_pkg_delivery_NodeEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event_type,pkg_arrival_event,event_type.pkg_arrival_event),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event_type,elevator_status_event,event_type.elevator_status_event),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event_type,delivery_status_event,event_type.delivery_status_event),   3)
#define smart_pkg_delivery_NodeEvent_CALLBACK NULL
#define smart_pkg_delivery_NodeEvent_DEFAULT NULL
#define smart_pkg_delivery_NodeEvent_event_type_pkg_arrival_event_MSGTYPE smart_pkg_delivery_PkgArrivalEvent
#define smart_pkg_delivery_NodeEvent_event_type_elevator_status_event_MSGTYPE smart_pkg_delivery_ElevatorStatusEvent
#define smart_pkg_delivery_NodeEvent_event_type_delivery_status_event_MSGTYPE smart_pkg_delivery_DeliveryStatusEvent

#define smart_pkg_delivery_AckStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status_code,       1) \
X(a, STATIC,   OPTIONAL, STRING,   message,           2)
#define smart_pkg_delivery_AckStatus_CALLBACK NULL
#define smart_pkg_delivery_AckStatus_DEFAULT NULL

#define smart_pkg_delivery_ExecutionStatus_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status_code,       1) \
X(a, STATIC,   OPTIONAL, STRING,   message,           2)
#define smart_pkg_delivery_ExecutionStatus_CALLBACK NULL
#define smart_pkg_delivery_ExecutionStatus_DEFAULT NULL

#define smart_pkg_delivery_ClientRegisterRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    identity_type,     1) \
X(a, STATIC,   OPTIONAL, UINT32,   identity_id,       2) \
X(a, CALLBACK, OPTIONAL, STRING,   identity_name,     3)
#define smart_pkg_delivery_ClientRegisterRequest_CALLBACK pb_default_field_callback
#define smart_pkg_delivery_ClientRegisterRequest_DEFAULT NULL

#define smart_pkg_delivery_ClientRegisterResponse_FIELDLIST(X, a) \

#define smart_pkg_delivery_ClientRegisterResponse_CALLBACK NULL
#define smart_pkg_delivery_ClientRegisterResponse_DEFAULT NULL

#define smart_pkg_delivery_GetPkgInfosRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   user_id,           1)
#define smart_pkg_delivery_GetPkgInfosRequest_CALLBACK NULL
#define smart_pkg_delivery_GetPkgInfosRequest_DEFAULT NULL

#define smart_pkg_delivery_GetPkgInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  pkgs,              1)
#define smart_pkg_delivery_GetPkgInfoResponse_CALLBACK NULL
#define smart_pkg_delivery_GetPkgInfoResponse_DEFAULT NULL
#define smart_pkg_delivery_GetPkgInfoResponse_pkgs_MSGTYPE smart_pkg_delivery_Pkg

#define smart_pkg_delivery_MoveDeliveryRobotRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   delivery_robot_id,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  destination_address,   2)
#define smart_pkg_delivery_MoveDeliveryRobotRequest_CALLBACK NULL
#define smart_pkg_delivery_MoveDeliveryRobotRequest_DEFAULT NULL
#define smart_pkg_delivery_MoveDeliveryRobotRequest_destination_address_MSGTYPE smart_pkg_delivery_AptAddress

#define smart_pkg_delivery_MoveDeliveryRobotResponse_FIELDLIST(X, a) \

#define smart_pkg_delivery_MoveDeliveryRobotResponse_CALLBACK NULL
#define smart_pkg_delivery_MoveDeliveryRobotResponse_DEFAULT NULL

#define smart_pkg_delivery_SetElevatorStatusRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   elevator_id,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  elevator_status,   2)
#define smart_pkg_delivery_SetElevatorStatusRequest_CALLBACK NULL
#define smart_pkg_delivery_SetElevatorStatusRequest_DEFAULT NULL
#define smart_pkg_delivery_SetElevatorStatusRequest_elevator_status_MSGTYPE smart_pkg_delivery_Elevator_Status

#define smart_pkg_delivery_SetElevatorStatusResponse_FIELDLIST(X, a) \

#define smart_pkg_delivery_SetElevatorStatusResponse_CALLBACK NULL
#define smart_pkg_delivery_SetElevatorStatusResponse_DEFAULT NULL

#define smart_pkg_delivery_PkgArrivalEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address,           1)
#define smart_pkg_delivery_PkgArrivalEvent_CALLBACK NULL
#define smart_pkg_delivery_PkgArrivalEvent_DEFAULT NULL
#define smart_pkg_delivery_PkgArrivalEvent_address_MSGTYPE smart_pkg_delivery_AptAddress

#define smart_pkg_delivery_ElevatorStatusEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   elevator_id,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  elevator_status,   2)
#define smart_pkg_delivery_ElevatorStatusEvent_CALLBACK NULL
#define smart_pkg_delivery_ElevatorStatusEvent_DEFAULT NULL
#define smart_pkg_delivery_ElevatorStatusEvent_elevator_status_MSGTYPE smart_pkg_delivery_Elevator_Status

#define smart_pkg_delivery_DeliveryStatusEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   delivery_robot_id,   1) \
X(a, STATIC,   OPTIONAL, UENUM,    delivery_status,   2)
#define smart_pkg_delivery_DeliveryStatusEvent_CALLBACK NULL
#define smart_pkg_delivery_DeliveryStatusEvent_DEFAULT NULL

#define smart_pkg_delivery_Elevator_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2)
#define smart_pkg_delivery_Elevator_CALLBACK NULL
#define smart_pkg_delivery_Elevator_DEFAULT NULL
#define smart_pkg_delivery_Elevator_status_MSGTYPE smart_pkg_delivery_Elevator_Status

#define smart_pkg_delivery_Elevator_Status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   current_floor,     1) \
X(a, STATIC,   OPTIONAL, UENUM,    door_open_status,   2)
#define smart_pkg_delivery_Elevator_Status_CALLBACK NULL
#define smart_pkg_delivery_Elevator_Status_DEFAULT NULL

#define smart_pkg_delivery_DeliveryRobot_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, UENUM,    delivery_status,   3)
#define smart_pkg_delivery_DeliveryRobot_CALLBACK NULL
#define smart_pkg_delivery_DeliveryRobot_DEFAULT NULL

#define smart_pkg_delivery_PkgRoom_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   REPEATED, MESSAGE,  lockers,           2)
#define smart_pkg_delivery_PkgRoom_CALLBACK NULL
#define smart_pkg_delivery_PkgRoom_DEFAULT NULL
#define smart_pkg_delivery_PkgRoom_lockers_MSGTYPE smart_pkg_delivery_PkgRoom_Locker

#define smart_pkg_delivery_PkgRoom_Locker_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   locker_id,         1) \
X(a, STATIC,   OPTIONAL, STRING,   access_code,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   pkg_id,            3)
#define smart_pkg_delivery_PkgRoom_Locker_CALLBACK NULL
#define smart_pkg_delivery_PkgRoom_Locker_DEFAULT NULL

#define smart_pkg_delivery_User_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address,           2)
#define smart_pkg_delivery_User_CALLBACK NULL
#define smart_pkg_delivery_User_DEFAULT NULL
#define smart_pkg_delivery_User_address_MSGTYPE smart_pkg_delivery_AptAddress

#define smart_pkg_delivery_Pkg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  address,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   sender_id,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   receiver_id,       4)
#define smart_pkg_delivery_Pkg_CALLBACK NULL
#define smart_pkg_delivery_Pkg_DEFAULT NULL
#define smart_pkg_delivery_Pkg_address_MSGTYPE smart_pkg_delivery_AptAddress

#define smart_pkg_delivery_AptAddress_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   apt_complex,       1) \
X(a, STATIC,   OPTIONAL, UINT32,   building_num,      2) \
X(a, STATIC,   OPTIONAL, UINT32,   unit_num,          3)
#define smart_pkg_delivery_AptAddress_CALLBACK NULL
#define smart_pkg_delivery_AptAddress_DEFAULT NULL

extern const pb_msgdesc_t smart_pkg_delivery_InteractionMsg_msg;
extern const pb_msgdesc_t smart_pkg_delivery_Request_msg;
extern const pb_msgdesc_t smart_pkg_delivery_Response_msg;
extern const pb_msgdesc_t smart_pkg_delivery_NodeEvent_msg;
extern const pb_msgdesc_t smart_pkg_delivery_AckStatus_msg;
extern const pb_msgdesc_t smart_pkg_delivery_ExecutionStatus_msg;
extern const pb_msgdesc_t smart_pkg_delivery_ClientRegisterRequest_msg;
extern const pb_msgdesc_t smart_pkg_delivery_ClientRegisterResponse_msg;
extern const pb_msgdesc_t smart_pkg_delivery_GetPkgInfosRequest_msg;
extern const pb_msgdesc_t smart_pkg_delivery_GetPkgInfoResponse_msg;
extern const pb_msgdesc_t smart_pkg_delivery_MoveDeliveryRobotRequest_msg;
extern const pb_msgdesc_t smart_pkg_delivery_MoveDeliveryRobotResponse_msg;
extern const pb_msgdesc_t smart_pkg_delivery_SetElevatorStatusRequest_msg;
extern const pb_msgdesc_t smart_pkg_delivery_SetElevatorStatusResponse_msg;
extern const pb_msgdesc_t smart_pkg_delivery_PkgArrivalEvent_msg;
extern const pb_msgdesc_t smart_pkg_delivery_ElevatorStatusEvent_msg;
extern const pb_msgdesc_t smart_pkg_delivery_DeliveryStatusEvent_msg;
extern const pb_msgdesc_t smart_pkg_delivery_Elevator_msg;
extern const pb_msgdesc_t smart_pkg_delivery_Elevator_Status_msg;
extern const pb_msgdesc_t smart_pkg_delivery_DeliveryRobot_msg;
extern const pb_msgdesc_t smart_pkg_delivery_PkgRoom_msg;
extern const pb_msgdesc_t smart_pkg_delivery_PkgRoom_Locker_msg;
extern const pb_msgdesc_t smart_pkg_delivery_User_msg;
extern const pb_msgdesc_t smart_pkg_delivery_Pkg_msg;
extern const pb_msgdesc_t smart_pkg_delivery_AptAddress_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define smart_pkg_delivery_InteractionMsg_fields &smart_pkg_delivery_InteractionMsg_msg
#define smart_pkg_delivery_Request_fields &smart_pkg_delivery_Request_msg
#define smart_pkg_delivery_Response_fields &smart_pkg_delivery_Response_msg
#define smart_pkg_delivery_NodeEvent_fields &smart_pkg_delivery_NodeEvent_msg
#define smart_pkg_delivery_AckStatus_fields &smart_pkg_delivery_AckStatus_msg
#define smart_pkg_delivery_ExecutionStatus_fields &smart_pkg_delivery_ExecutionStatus_msg
#define smart_pkg_delivery_ClientRegisterRequest_fields &smart_pkg_delivery_ClientRegisterRequest_msg
#define smart_pkg_delivery_ClientRegisterResponse_fields &smart_pkg_delivery_ClientRegisterResponse_msg
#define smart_pkg_delivery_GetPkgInfosRequest_fields &smart_pkg_delivery_GetPkgInfosRequest_msg
#define smart_pkg_delivery_GetPkgInfoResponse_fields &smart_pkg_delivery_GetPkgInfoResponse_msg
#define smart_pkg_delivery_MoveDeliveryRobotRequest_fields &smart_pkg_delivery_MoveDeliveryRobotRequest_msg
#define smart_pkg_delivery_MoveDeliveryRobotResponse_fields &smart_pkg_delivery_MoveDeliveryRobotResponse_msg
#define smart_pkg_delivery_SetElevatorStatusRequest_fields &smart_pkg_delivery_SetElevatorStatusRequest_msg
#define smart_pkg_delivery_SetElevatorStatusResponse_fields &smart_pkg_delivery_SetElevatorStatusResponse_msg
#define smart_pkg_delivery_PkgArrivalEvent_fields &smart_pkg_delivery_PkgArrivalEvent_msg
#define smart_pkg_delivery_ElevatorStatusEvent_fields &smart_pkg_delivery_ElevatorStatusEvent_msg
#define smart_pkg_delivery_DeliveryStatusEvent_fields &smart_pkg_delivery_DeliveryStatusEvent_msg
#define smart_pkg_delivery_Elevator_fields &smart_pkg_delivery_Elevator_msg
#define smart_pkg_delivery_Elevator_Status_fields &smart_pkg_delivery_Elevator_Status_msg
#define smart_pkg_delivery_DeliveryRobot_fields &smart_pkg_delivery_DeliveryRobot_msg
#define smart_pkg_delivery_PkgRoom_fields &smart_pkg_delivery_PkgRoom_msg
#define smart_pkg_delivery_PkgRoom_Locker_fields &smart_pkg_delivery_PkgRoom_Locker_msg
#define smart_pkg_delivery_User_fields &smart_pkg_delivery_User_msg
#define smart_pkg_delivery_Pkg_fields &smart_pkg_delivery_Pkg_msg
#define smart_pkg_delivery_AptAddress_fields &smart_pkg_delivery_AptAddress_msg

/* Maximum encoded size of messages (where known) */
/* smart_pkg_delivery_InteractionMsg_size depends on runtime parameters */
/* smart_pkg_delivery_Request_size depends on runtime parameters */
/* smart_pkg_delivery_ClientRegisterRequest_size depends on runtime parameters */
#define SMART_PKG_DELIVERY_SMART_PKG_DELIVERY_PB_H_MAX_SIZE smart_pkg_delivery_Response_size
#define smart_pkg_delivery_AckStatus_size        260
#define smart_pkg_delivery_AptAddress_size       142
#define smart_pkg_delivery_ClientRegisterResponse_size 0
#define smart_pkg_delivery_DeliveryRobot_size    8
#define smart_pkg_delivery_DeliveryStatusEvent_size 8
#define smart_pkg_delivery_ElevatorStatusEvent_size 16
#define smart_pkg_delivery_Elevator_Status_size  8
#define smart_pkg_delivery_Elevator_size         16
#define smart_pkg_delivery_ExecutionStatus_size  260
#define smart_pkg_delivery_GetPkgInfoResponse_size 1660
#define smart_pkg_delivery_GetPkgInfosRequest_size 6
#define smart_pkg_delivery_MoveDeliveryRobotRequest_size 151
#define smart_pkg_delivery_MoveDeliveryRobotResponse_size 0
#define smart_pkg_delivery_NodeEvent_size        148
#define smart_pkg_delivery_PkgArrivalEvent_size  145
#define smart_pkg_delivery_PkgRoom_Locker_size   45
#define smart_pkg_delivery_PkgRoom_size          476
#define smart_pkg_delivery_Pkg_size              163
#define smart_pkg_delivery_Response_size         2189
#define smart_pkg_delivery_SetElevatorStatusRequest_size 16
#define smart_pkg_delivery_SetElevatorStatusResponse_size 0
#define smart_pkg_delivery_User_size             151

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
