/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "smart_pkg_delivery.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smart_pkg_delivery_InteractionMsg, smart_pkg_delivery_InteractionMsg, 2)


PB_BIND(smart_pkg_delivery_Request, smart_pkg_delivery_Request, AUTO)


PB_BIND(smart_pkg_delivery_Response, smart_pkg_delivery_Response, 2)


PB_BIND(smart_pkg_delivery_NodeEvent, smart_pkg_delivery_NodeEvent, AUTO)


PB_BIND(smart_pkg_delivery_AckStatus, smart_pkg_delivery_AckStatus, 2)


PB_BIND(smart_pkg_delivery_ExecutionStatus, smart_pkg_delivery_ExecutionStatus, 2)


PB_BIND(smart_pkg_delivery_ClientRegisterRequest, smart_pkg_delivery_ClientRegisterRequest, AUTO)


PB_BIND(smart_pkg_delivery_ClientRegisterResponse, smart_pkg_delivery_ClientRegisterResponse, AUTO)


PB_BIND(smart_pkg_delivery_GetPkgInfosRequest, smart_pkg_delivery_GetPkgInfosRequest, AUTO)


PB_BIND(smart_pkg_delivery_GetPkgInfoResponse, smart_pkg_delivery_GetPkgInfoResponse, 2)


PB_BIND(smart_pkg_delivery_MoveDeliveryRobotRequest, smart_pkg_delivery_MoveDeliveryRobotRequest, AUTO)


PB_BIND(smart_pkg_delivery_MoveDeliveryRobotResponse, smart_pkg_delivery_MoveDeliveryRobotResponse, AUTO)


PB_BIND(smart_pkg_delivery_SetElevatorStatusRequest, smart_pkg_delivery_SetElevatorStatusRequest, AUTO)


PB_BIND(smart_pkg_delivery_SetElevatorStatusResponse, smart_pkg_delivery_SetElevatorStatusResponse, AUTO)


PB_BIND(smart_pkg_delivery_PkgArrivalEvent, smart_pkg_delivery_PkgArrivalEvent, AUTO)


PB_BIND(smart_pkg_delivery_ElevatorStatusEvent, smart_pkg_delivery_ElevatorStatusEvent, AUTO)


PB_BIND(smart_pkg_delivery_DeliveryStatusEvent, smart_pkg_delivery_DeliveryStatusEvent, AUTO)


PB_BIND(smart_pkg_delivery_Elevator, smart_pkg_delivery_Elevator, AUTO)


PB_BIND(smart_pkg_delivery_Elevator_Status, smart_pkg_delivery_Elevator_Status, AUTO)


PB_BIND(smart_pkg_delivery_DeliveryRobot, smart_pkg_delivery_DeliveryRobot, AUTO)


PB_BIND(smart_pkg_delivery_PkgRoom, smart_pkg_delivery_PkgRoom, 2)


PB_BIND(smart_pkg_delivery_PkgRoom_Locker, smart_pkg_delivery_PkgRoom_Locker, AUTO)


PB_BIND(smart_pkg_delivery_User, smart_pkg_delivery_User, AUTO)


PB_BIND(smart_pkg_delivery_Pkg, smart_pkg_delivery_Pkg, AUTO)


PB_BIND(smart_pkg_delivery_AptAddress, smart_pkg_delivery_AptAddress, AUTO)













