
Fan: {
  On -> Off: B1 | B4 | USART
  Off -> On.Manual.Speed.Low: B2 | USART

  On: {
    Manual: {
      Speed: {
        Low -> Medium -> High -> Low: B2 | USART
      }
    }
    Auto: {
      Type1 -> Type2 -> Type1: B3 | USART
    }

    Manual -> Auto: B2 | UART
    Manual <- Auto: B3 | UART
  }
  Off

}


Fan.**.shape: circle
# B1: Button 1 (Off)
# B2: Button 2 (Manual entry point, Speed 1 ~ 3 control)
# B2: Button 3 (Auto entry point | Manual mode toggle)
# B3: Button 4 (Shutdown Timer setting: None, 3 minute, 5 minute, 7 minute)

# ELK layout engine TALA.. is not free when use as commercial
# 크기 설정이 안됨.. Tala layout 엔진은 https://app.terrastruct.com/diagrams/1025965684/edit 페이지에서 테스트해봐야함..
# ELK 엔진 문제점.. 키가 레이블에 가려짐..
# DAGRE 엔진 문제점..  배치에 따라 connection 화살표가 안보임.
# 