services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "11311:11311" # ROS master - Port mapping
    env_file:
      - .devcontainer/devcontainer.env
    environment:
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - TURTLEBOT3_MODEL=burger
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      # ✔️ fix some QT bugs ; https://wiki.ros.org/docker/Tutorials/Compose
      - QT_X11_NO_MITSHM=1
      - WORKSPACE_DIR=/workspace # ❗
    volumes:
      - .:/workspace
      # Shares the X11 Unix socket to enable GUI forwarding in the container. RW (Read, Write) is required for bidirectional communication.
      # - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Provides X authority file to authenticate GUI apps with the X server. No RW (Read, Write) needed as it's typically read-only.
      # - ${HOME}/.Xauthority:/tmp/.Xauthority:ro
    devices:
      - /dev/video0     # Access to video input devices
      - /dev/ttyACM0    # Access to serial devices
      - /dev/ttyACM1
    networks:
      ros_network:
        ipv4_address: 172.18.0.2
      # 🧪: may be required to access hardware and devices fully
    privileged: true
    # 🔰 Allocate a pseudo-TTY for development
    tty: true
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 4gb
        reservations:
          cpus: "0.20"
          memory: 2gb
          devices:
            - capabilities:
                - gpu
    runtime: nvidia
    # ❔ `container_name`: Sets the explicit name of the Docker container for easier identification and management.
    # container_name: ros_noetic_turtlebot3-node_master


# https://docs.docker.com/reference/compose-file/networks
networks:   
  # It will create name '<project_name>_<network_name>'
  ros_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
    # ❔ `attachable`: Allows standalone containers to dynamically attach to this network.
    attachable: true
