SELECT
  TABLE_NAME,
  COLUMN_NAME,
  DATA_TYPE,
  IS_NULLABLE,
  COLUMN_KEY,
  EXTRA,
  COLUMN_COMMENT
FROM
  INFORMATION_SCHEMA.COLUMNS
WHERE
  TABLE_SCHEMA = 'smart_parcel'
ORDER BY
  TABLE_NAME,
  ORDINAL_POSITION;