/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "smart_parcel.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smart_parcel_Request, smart_parcel_Request, AUTO)


PB_BIND(smart_parcel_Request_PayloadEntry, smart_parcel_Request_PayloadEntry, AUTO)


PB_BIND(smart_parcel_Elevator, smart_parcel_Elevator, AUTO)


PB_BIND(smart_parcel_Elevator_Status, smart_parcel_Elevator_Status, AUTO)


PB_BIND(smart_parcel_DeliveryRobot, smart_parcel_DeliveryRobot, AUTO)


PB_BIND(smart_parcel_DeliveryRobot_Status, smart_parcel_DeliveryRobot_Status, AUTO)


PB_BIND(smart_parcel_Storage, smart_parcel_Storage, AUTO)


PB_BIND(smart_parcel_Storage_Locker, smart_parcel_Storage_Locker, AUTO)


PB_BIND(smart_parcel_User, smart_parcel_User, AUTO)







