/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SMART_PARCEL_SMART_PARCEL_PB_H_INCLUDED
#define PB_SMART_PARCEL_SMART_PARCEL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _smart_parcel_Elevator_DoorOpenStatus {
    smart_parcel_Elevator_DoorOpenStatus_CLOSED = 0,
    smart_parcel_Elevator_DoorOpenStatus_OPEN = 1
} smart_parcel_Elevator_DoorOpenStatus;

typedef enum _smart_parcel_DeliveryRobot_DeliveryStatus {
    smart_parcel_DeliveryRobot_DeliveryStatus_READY = 0,
    smart_parcel_DeliveryRobot_DeliveryStatus_BUSY = 1,
    smart_parcel_DeliveryRobot_DeliveryStatus_COMPLETE = 2
} smart_parcel_DeliveryRobot_DeliveryStatus;

/* Struct definitions */
typedef struct _smart_parcel_Request {
    pb_callback_t source;
    pb_callback_t destination;
    pb_callback_t command;
    pb_callback_t payload; /* string status = 5;
 repeated Link links = 6; */
} smart_parcel_Request;

typedef struct _smart_parcel_Request_PayloadEntry {
    pb_callback_t key;
    pb_callback_t value;
} smart_parcel_Request_PayloadEntry;

typedef struct _smart_parcel_Elevator_Status {
    pb_callback_t current_floor;
    bool has_door_open_status;
    smart_parcel_Elevator_DoorOpenStatus door_open_status;
} smart_parcel_Elevator_Status;

typedef struct _smart_parcel_Elevator {
    bool has_id;
    uint32_t id;
    bool has_status;
    smart_parcel_Elevator_Status status;
} smart_parcel_Elevator;

typedef struct _smart_parcel_DeliveryRobot_Status {
    bool has_status;
    smart_parcel_DeliveryRobot_DeliveryStatus status;
} smart_parcel_DeliveryRobot_Status;

/* command: set, ack, send, ... 📰
 🚗 */
typedef struct _smart_parcel_DeliveryRobot {
    bool has_id;
    uint32_t id;
    bool has_status;
    smart_parcel_DeliveryRobot_Status status;
} smart_parcel_DeliveryRobot;

typedef struct _smart_parcel_Storage {
    bool has_id;
    uint32_t id;
    pb_callback_t lockers;
} smart_parcel_Storage;

typedef struct _smart_parcel_Storage_Locker {
    bool has_locker_id;
    uint32_t locker_id;
    pb_callback_t access_code;
    bool has_parcel_id;
    uint32_t parcel_id;
} smart_parcel_Storage_Locker;

/* Wall Pad */
typedef struct _smart_parcel_User {
    bool has_id;
    uint32_t id;
} smart_parcel_User;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _smart_parcel_Elevator_DoorOpenStatus_MIN smart_parcel_Elevator_DoorOpenStatus_CLOSED
#define _smart_parcel_Elevator_DoorOpenStatus_MAX smart_parcel_Elevator_DoorOpenStatus_OPEN
#define _smart_parcel_Elevator_DoorOpenStatus_ARRAYSIZE ((smart_parcel_Elevator_DoorOpenStatus)(smart_parcel_Elevator_DoorOpenStatus_OPEN+1))

#define _smart_parcel_DeliveryRobot_DeliveryStatus_MIN smart_parcel_DeliveryRobot_DeliveryStatus_READY
#define _smart_parcel_DeliveryRobot_DeliveryStatus_MAX smart_parcel_DeliveryRobot_DeliveryStatus_COMPLETE
#define _smart_parcel_DeliveryRobot_DeliveryStatus_ARRAYSIZE ((smart_parcel_DeliveryRobot_DeliveryStatus)(smart_parcel_DeliveryRobot_DeliveryStatus_COMPLETE+1))




#define smart_parcel_Elevator_Status_door_open_status_ENUMTYPE smart_parcel_Elevator_DoorOpenStatus


#define smart_parcel_DeliveryRobot_Status_status_ENUMTYPE smart_parcel_DeliveryRobot_DeliveryStatus





/* Initializer values for message structs */
#define smart_parcel_Request_init_default        {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define smart_parcel_Request_PayloadEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define smart_parcel_Elevator_init_default       {false, 0, false, smart_parcel_Elevator_Status_init_default}
#define smart_parcel_Elevator_Status_init_default {{{NULL}, NULL}, false, _smart_parcel_Elevator_DoorOpenStatus_MIN}
#define smart_parcel_DeliveryRobot_init_default  {false, 0, false, smart_parcel_DeliveryRobot_Status_init_default}
#define smart_parcel_DeliveryRobot_Status_init_default {false, _smart_parcel_DeliveryRobot_DeliveryStatus_MIN}
#define smart_parcel_Storage_init_default        {false, 0, {{NULL}, NULL}}
#define smart_parcel_Storage_Locker_init_default {false, 0, {{NULL}, NULL}, false, 0}
#define smart_parcel_User_init_default           {false, 0}
#define smart_parcel_Request_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define smart_parcel_Request_PayloadEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define smart_parcel_Elevator_init_zero          {false, 0, false, smart_parcel_Elevator_Status_init_zero}
#define smart_parcel_Elevator_Status_init_zero   {{{NULL}, NULL}, false, _smart_parcel_Elevator_DoorOpenStatus_MIN}
#define smart_parcel_DeliveryRobot_init_zero     {false, 0, false, smart_parcel_DeliveryRobot_Status_init_zero}
#define smart_parcel_DeliveryRobot_Status_init_zero {false, _smart_parcel_DeliveryRobot_DeliveryStatus_MIN}
#define smart_parcel_Storage_init_zero           {false, 0, {{NULL}, NULL}}
#define smart_parcel_Storage_Locker_init_zero    {false, 0, {{NULL}, NULL}, false, 0}
#define smart_parcel_User_init_zero              {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define smart_parcel_Request_source_tag          1
#define smart_parcel_Request_destination_tag     2
#define smart_parcel_Request_command_tag         3
#define smart_parcel_Request_payload_tag         4
#define smart_parcel_Request_PayloadEntry_key_tag 1
#define smart_parcel_Request_PayloadEntry_value_tag 2
#define smart_parcel_Elevator_Status_current_floor_tag 1
#define smart_parcel_Elevator_Status_door_open_status_tag 2
#define smart_parcel_Elevator_id_tag             1
#define smart_parcel_Elevator_status_tag         2
#define smart_parcel_DeliveryRobot_Status_status_tag 2
#define smart_parcel_DeliveryRobot_id_tag        1
#define smart_parcel_DeliveryRobot_status_tag    2
#define smart_parcel_Storage_id_tag              1
#define smart_parcel_Storage_lockers_tag         2
#define smart_parcel_Storage_Locker_locker_id_tag 1
#define smart_parcel_Storage_Locker_access_code_tag 2
#define smart_parcel_Storage_Locker_parcel_id_tag 3
#define smart_parcel_User_id_tag                 1

/* Struct field encoding specification for nanopb */
#define smart_parcel_Request_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   source,            1) \
X(a, CALLBACK, OPTIONAL, STRING,   destination,       2) \
X(a, CALLBACK, OPTIONAL, STRING,   command,           3) \
X(a, CALLBACK, REPEATED, MESSAGE,  payload,           4)
#define smart_parcel_Request_CALLBACK pb_default_field_callback
#define smart_parcel_Request_DEFAULT NULL
#define smart_parcel_Request_payload_MSGTYPE smart_parcel_Request_PayloadEntry

#define smart_parcel_Request_PayloadEntry_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   key,               1) \
X(a, CALLBACK, OPTIONAL, STRING,   value,             2)
#define smart_parcel_Request_PayloadEntry_CALLBACK pb_default_field_callback
#define smart_parcel_Request_PayloadEntry_DEFAULT NULL

#define smart_parcel_Elevator_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2)
#define smart_parcel_Elevator_CALLBACK NULL
#define smart_parcel_Elevator_DEFAULT NULL
#define smart_parcel_Elevator_status_MSGTYPE smart_parcel_Elevator_Status

#define smart_parcel_Elevator_Status_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   current_floor,     1) \
X(a, STATIC,   OPTIONAL, UENUM,    door_open_status,   2)
#define smart_parcel_Elevator_Status_CALLBACK pb_default_field_callback
#define smart_parcel_Elevator_Status_DEFAULT NULL

#define smart_parcel_DeliveryRobot_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            2)
#define smart_parcel_DeliveryRobot_CALLBACK NULL
#define smart_parcel_DeliveryRobot_DEFAULT NULL
#define smart_parcel_DeliveryRobot_status_MSGTYPE smart_parcel_DeliveryRobot_Status

#define smart_parcel_DeliveryRobot_Status_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    status,            2)
#define smart_parcel_DeliveryRobot_Status_CALLBACK NULL
#define smart_parcel_DeliveryRobot_Status_DEFAULT NULL

#define smart_parcel_Storage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1) \
X(a, CALLBACK, REPEATED, MESSAGE,  lockers,           2)
#define smart_parcel_Storage_CALLBACK pb_default_field_callback
#define smart_parcel_Storage_DEFAULT NULL
#define smart_parcel_Storage_lockers_MSGTYPE smart_parcel_Storage_Locker

#define smart_parcel_Storage_Locker_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   locker_id,         1) \
X(a, CALLBACK, OPTIONAL, STRING,   access_code,       2) \
X(a, STATIC,   OPTIONAL, UINT32,   parcel_id,         3)
#define smart_parcel_Storage_Locker_CALLBACK pb_default_field_callback
#define smart_parcel_Storage_Locker_DEFAULT NULL

#define smart_parcel_User_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   id,                1)
#define smart_parcel_User_CALLBACK NULL
#define smart_parcel_User_DEFAULT NULL

extern const pb_msgdesc_t smart_parcel_Request_msg;
extern const pb_msgdesc_t smart_parcel_Request_PayloadEntry_msg;
extern const pb_msgdesc_t smart_parcel_Elevator_msg;
extern const pb_msgdesc_t smart_parcel_Elevator_Status_msg;
extern const pb_msgdesc_t smart_parcel_DeliveryRobot_msg;
extern const pb_msgdesc_t smart_parcel_DeliveryRobot_Status_msg;
extern const pb_msgdesc_t smart_parcel_Storage_msg;
extern const pb_msgdesc_t smart_parcel_Storage_Locker_msg;
extern const pb_msgdesc_t smart_parcel_User_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define smart_parcel_Request_fields &smart_parcel_Request_msg
#define smart_parcel_Request_PayloadEntry_fields &smart_parcel_Request_PayloadEntry_msg
#define smart_parcel_Elevator_fields &smart_parcel_Elevator_msg
#define smart_parcel_Elevator_Status_fields &smart_parcel_Elevator_Status_msg
#define smart_parcel_DeliveryRobot_fields &smart_parcel_DeliveryRobot_msg
#define smart_parcel_DeliveryRobot_Status_fields &smart_parcel_DeliveryRobot_Status_msg
#define smart_parcel_Storage_fields &smart_parcel_Storage_msg
#define smart_parcel_Storage_Locker_fields &smart_parcel_Storage_Locker_msg
#define smart_parcel_User_fields &smart_parcel_User_msg

/* Maximum encoded size of messages (where known) */
/* smart_parcel_Request_size depends on runtime parameters */
/* smart_parcel_Request_PayloadEntry_size depends on runtime parameters */
/* smart_parcel_Elevator_size depends on runtime parameters */
/* smart_parcel_Elevator_Status_size depends on runtime parameters */
/* smart_parcel_Storage_size depends on runtime parameters */
/* smart_parcel_Storage_Locker_size depends on runtime parameters */
#define SMART_PARCEL_SMART_PARCEL_PB_H_MAX_SIZE  smart_parcel_DeliveryRobot_size
#define smart_parcel_DeliveryRobot_Status_size   2
#define smart_parcel_DeliveryRobot_size          10
#define smart_parcel_User_size                   6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
