/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "fileproto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ListFilesRequest, ListFilesRequest, AUTO)


PB_BIND(FileInfo, FileInfo, AUTO)


PB_BIND(ListFilesResponse, ListFilesResponse, AUTO)



