# Use Debian 12 (Bookworm) as the base image
FROM debian:bookworm

# Avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update and install necessary packages
RUN { \
  echo Hi && \
  set -e && \
  apt-get update && apt-get install -y \
  wget \
  git \
  build-essential \
  make \
  cmake \
  rsync \
  sed \
  libclang-dev \
  ninja-build \
  gcc \
  bison \
  python3 \
  gperf \
  pkg-config \
  libfontconfig1-dev \
  libfreetype6-dev \
  libx11-dev \
  libx11-xcb-dev \
  libxext-dev \
  libxfixes-dev \
  libxi-dev \
  libxrender-dev \
  libxcb1-dev \
  libxcb-glx0-dev \
  libxcb-keysyms1-dev \
  libxcb-image0-dev \
  libxcb-shm0-dev \
  libxcb-icccm4-dev \
  libxcb-sync-dev \
  libxcb-xfixes0-dev \
  libxcb-shape0-dev \
  libxcb-randr0-dev \
  libxcb-render-util0-dev \
  libxcb-util-dev \
  libxcb-xinerama0-dev \
  libxcb-xkb-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev \
  libatspi2.0-dev \
  libgl1-mesa-dev \
  libglu1-mesa-dev \
  freeglut3-dev \
  libssl-dev \
  libgmp-dev \
  libmpfr-dev \
  libmpc-dev \
  flex \
  gawk \
  texinfo \
  libisl-dev \
  zlib1g-dev \
  libtool \
  autoconf \
  automake \
  libgdbm-dev \
  libdb-dev \
  libbz2-dev \
  libreadline-dev \
  libexpat1-dev \
  liblzma-dev \
  libffi-dev \
  libsqlite3-dev \
  libbsd-dev \
  perl \
  patch \
  m4 \
  libncurses5-dev \
  gettext  \
  gcc-arm-linux-gnueabihf \
  g++-arm-linux-gnueabihf \
  binutils-arm-linux-gnueabihf \
  libc6-armhf-cross \
  libc6-dev-armhf-cross \
  glibc-source; \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*; \
  } 2>&1 | tee -a /build.log

# Set the working directory to /build
WORKDIR /build

# Create sysroot directory
RUN mkdir sysroot sysroot/usr sysroot/opt

# Copy Raspberry Pi sysroot tarball (if available)
COPY rasp.tar.gz /build/rasp.tar.gz
RUN tar xvfz /build/rasp.tar.gz -C /build/sysroot

# Copy the toolchain file
COPY toolchain.cmake /build/

# Build and install CMake from source
RUN { \
  echo "Building CMake from source" && \
  mkdir cmakeBuild && cd cmakeBuild && \
  git clone https://github.com/Kitware/CMake.git && \
  cd CMake && \
  ./bootstrap && make -j$(nproc) && make install && \
  echo "CMake build completed"; \
  } 2>&1 | tee -a /build.log


# Fix symbolic link and prepare directories
RUN { \
  set -e && \
  echo "Fix symbolic link and create directories" && \
  wget https://raw.githubusercontent.com/riscv/riscv-poky/master/scripts/sysroot-relativelinks.py && \
  chmod +x sysroot-relativelinks.py && \
  python3 sysroot-relativelinks.py /build/sysroot && \
  mkdir -p qt6 qt6/host qt6/pi qt6/host-build qt6/pi-build qt6/src; \
  } 2>&1 | tee -a /build.log

### Download required submodules
RUN { set -e && cd qt6/src && \
  wget https://download.qt.io/official_releases/qt/6.8/6.8.0/submodules/qtbase-everywhere-src-6.8.0.tar.xz; \
  } 2>&1 | tee -a /build.log

# Download qtshadertools submodule
RUN { set -e && cd qt6/src && \
  wget https://download.qt.io/official_releases/qt/6.8/6.8.0/submodules/qtshadertools-everywhere-src-6.8.0.tar.xz; \
  } 2>&1 | tee -a /build.log

# Download qtdeclarative submodule
RUN { set -e && cd qt6/src && \
  wget https://download.qt.io/official_releases/qt/6.8/6.8.0/submodules/qtdeclarative-everywhere-src-6.8.0.tar.xz; \
  } 2>&1 | tee -a /build.log


# Extract and prepare host build
RUN { \
  set -e && \
  echo "Extract Qt modules for host build" && \
  cd qt6/host-build && \
  tar xf ../src/qtbase-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtshadertools-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtwebview-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtwebsockets-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtwebengine-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtwebchannel-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtwayland-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtvirtualkeyboard-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qttranslations-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qttools-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtsvg-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtspeech-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtserialport-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtserialbus-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtsensors-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtscxml-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtremoteobjects-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtquicktimeline-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtquickeffectmaker-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtquick3dphysics-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtquick3d-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtpositioning-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtnetworkauth-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtmultimedia-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtlottie-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtlocation-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtlanguageserver-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtimageformats-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qthttpserver-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtgrpc-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtgraphs-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtdoc-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtdatavis3d-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtconnectivity-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtcharts-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtactiveqt-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qt5compat-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qt3d-everywhere-src-6.8.0.tar.xz && \
  tar xf ../src/qtdeclarative-everywhere-src-6.8.0.tar.xz; \
  } 2>&1 | tee -a /build.log

# Compile qtbase for host
RUN { \
  set -e && \
  echo "Compile qtbase for host" && \
  cd qt6/host-build/qtbase-everywhere-src-6.8.0 && \
  cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF \
  -DCMAKE_INSTALL_PREFIX=/build/qt6/host && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtshadertools, qtwebview, qtwebsockets for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtshadertools for Raspberry Pi" && \
  cd qt6/pi-build/qtshadertools-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtwebview for Raspberry Pi" && \
  cd ../qtwebview-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtwebsockets for Raspberry Pi" && \
  cd ../qtwebsockets-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtwebengine, qtwebchannel, qtwayland for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtwebengine for Raspberry Pi" && \
  cd qt6/pi-build/qtwebengine-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtwebchannel for Raspberry Pi" && \
  cd ../qtwebchannel-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtwayland for Raspberry Pi" && \
  cd ../qtwayland-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtvirtualkeyboard, qttranslations, qttools for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtvirtualkeyboard for Raspberry Pi" && \
  cd qt6/pi-build/qtvirtualkeyboard-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qttranslations for Raspberry Pi" && \
  cd ../qttranslations-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qttools for Raspberry Pi" && \
  cd ../qttools-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtsvg, qtspeech, qtserialport for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtsvg for Raspberry Pi" && \
  cd qt6/pi-build/qtsvg-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtspeech for Raspberry Pi" && \
  cd ../qtspeech-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtserialport for Raspberry Pi" && \
  cd ../qtserialport-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtserialbus, qtsensors, qtscxml for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtserialbus for Raspberry Pi" && \
  cd qt6/pi-build/qtserialbus-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtsensors for Raspberry Pi" && \
  cd ../qtsensors-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtscxml for Raspberry Pi" && \
  cd ../qtscxml-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtremoteobjects, qtquicktimeline, qtquickeffectmaker for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtremoteobjects for Raspberry Pi" && \
  cd qt6/pi-build/qtremoteobjects-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtquicktimeline for Raspberry Pi" && \
  cd ../qtquicktimeline-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtquickeffectmaker for Raspberry Pi" && \
  cd ../qtquickeffectmaker-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtquick3dphysics, qtquick3d, qtpositioning for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtquick3dphysics for Raspberry Pi" && \
  cd qt6/pi-build/qtquick3dphysics-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtquick3d for Raspberry Pi" && \
  cd ../qtquick3d-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtpositioning for Raspberry Pi" && \
  cd ../qtpositioning-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtnetworkauth, qtmultimedia, qtlottie for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtnetworkauth for Raspberry Pi" && \
  cd qt6/pi-build/qtnetworkauth-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtmultimedia for Raspberry Pi" && \
  cd ../qtmultimedia-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtlottie for Raspberry Pi" && \
  cd ../qtlottie-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtlocation, qtlanguageserver, qtimageformats for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtlocation for Raspberry Pi" && \
  cd qt6/pi-build/qtlocation-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtlanguageserver for Raspberry Pi" && \
  cd ../qtlanguageserver-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtimageformats for Raspberry Pi" && \
  cd ../qtimageformats-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qthttpserver, qtgrpc, qtgraphs for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qthttpserver for Raspberry Pi" && \
  cd qt6/pi-build/qthttpserver-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtgrpc for Raspberry Pi" && \
  cd ../qtgrpc-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtgraphs for Raspberry Pi" && \
  cd ../qtgraphs-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtdoc, qtdatavis3d, qtconnectivity for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtdoc for Raspberry Pi" && \
  cd qt6/pi-build/qtdoc-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtdatavis3d for Raspberry Pi" && \
  cd ../qtdatavis3d-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtconnectivity for Raspberry Pi" && \
  cd ../qtconnectivity-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qtcharts, qtactiveqt, qt5compat for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qtcharts for Raspberry Pi" && \
  cd qt6/pi-build/qtcharts-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtactiveqt for Raspberry Pi" && \
  cd ../qtactiveqt-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qt5compat for Raspberry Pi" && \
  cd ../qt5compat-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Compile qt3d, qtdeclarative for Raspberry Pi
RUN { \
  set -e && \
  echo "Compile qt3d for Raspberry Pi" && \
  cd qt6/pi-build/qt3d-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  echo "Compile qtdeclarative for Raspberry Pi" && \
  cd ../qtdeclarative-everywhere-src-6.8.0 && \
  /build/qt6/pi/bin/qt-configure-module . && \
  cmake --build . --parallel 4 && \
  cmake --install .; \
  } 2>&1 | tee -a /build.log

# Final step: Compilation finished
RUN { \
  set -e && \
  echo "Compilation is finished"; \
  } 2>&1 | tee -a /build.log


RUN tar -czvf qt-host-binaries.tar.gz -C /build/qt6/host .
RUN tar -czvf qt-pi-binaries.tar.gz -C /build/qt6/pi .

# Set up project directory
RUN mkdir /build/project
COPY project /build/project

# Build the project using Qt for Raspberry Pi
RUN { \
  cd /build/project && \
  /build/qt6/pi/bin/qt-cmake . && \
  cmake --build .; \
  } 2>&1 | tee -a /build.log
